import type { Metadata } from 'next';
import { RunDetailPage } from './RunDetailPage';
import { publicGet } from '@/lib/server-api';
import { formatRunDate, runHeading } from '@/lib/runs';
import type { RunDetail } from '@/lib/types';
import { shareMetadata } from '@/lib/share-metadata';

// A server shell around the interactive run page, so a shared run link carries
// a title and an Open Graph card (D50). Only a Server Component can produce
// metadata, and the page itself has to be a Client Component — it RSVPs,
// checks people in and runs the Circle.
//
// The fetch here is deliberately unauthenticated. Metadata is what a link
// preview shows, and a preview is generated by whatever fetched the URL — a
// WhatsApp crawler, not the member who sent it. Asking as nobody is therefore
// both the honest question and the safe one: a members-only run yields nothing
// and gets a generic card rather than leaking its theme and meeting point into
// a group chat.

async function load(id: string) {
  return publicGet<{ run: RunDetail }>(`/runs/${id}`).catch(() => null);
}

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const data = await load(id);
  // Null covers both "no such run" and "not yours to see". Neither gets a
  // title that says which, and neither says "not found" — a member opening
  // their own kennel's members-only run would see that lie in the tab.
  if (!data) return shareMetadata({ title: 'Run', description: 'A run on Shiggy Trails.' });

  const run = data.run;
  const hares = run.hares.map((h) => h.displayName).filter(Boolean);
  const where = run.meetingPointName ?? run.city;
  const description = [
    formatRunDate(run.startsAt, run.timeZone),
    where,
    hares.length ? `Hare${hares.length > 1 ? 's' : ''}: ${hares.join(', ')}` : null,
    run.hashCash ? `Hash cash ${run.hashCash}` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  return shareMetadata({
    title: `${runHeading(run)} — ${run.kennel.shortName}`,
    description: run.theme ? `${run.theme}. ${description}` : description,
    image: run.posterUrl,
  });
}

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <RunDetailPage id={id} />;
}
